services:
  - type: web
    name: white-ecom-backend
    runtime: image
    region: frankfurt
    plan: free
    image:
      url: ghcr.io/senankponjosuekpodekon/white_ecom/backend:dev
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "9000"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: STORE_CORS
        sync: false
      - key: ADMIN_CORS
        sync: false
      - key: AUTH_CORS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: COOKIE_SECURE
        value: "true"
      - key: COOKIE_SAME_SITE
        value: "lax"
      - key: COOKIE_HTTP_ONLY
        value: "true"
      - key: SITE_URL
        sync: false
      - key: CLIENT_NAME
        value: "default"
      - key: STORE_NAME
        value: "White Shop"
      - key: DEFAULT_LANGUAGE
        value: "fr"
      - key: SUPPORTED_LANGUAGES
        value: "fr,en"
      - key: DESIGN_PRESET
        value: "modern"
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CREATE_DEFAULT_ADMIN
        value: "false"
